version: "3.8"

services:
  api:
    build: ./api/
    container_name: api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --root-path /api --proxy-headers
    volumes:
      - ${CHANNELSDB_DATA:-/data}:/data:ro

  web:
    container_name: web
    build: .
    depends_on:
      - api
    ports:
      - "${CHANNELSDB_PORT:-80}:80"
