name: channelsdb

services:
  api:
    volumes:
      - /data:/data:ro
    restart: always

  web:
    volumes:
      - ./nginx.production.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/channelsdb.ncbr.muni.cz/fullchain.pem:/etc/fullchain.pem:ro
      - /etc/letsencrypt/live/channelsdb.ncbr.muni.cz/privkey.pem:/etc/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
