version: "3.8"

services:
  api:
    build: ../api
    container_name: api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --root-path /api --proxy-headers
    volumes:
      - /data:/data:ro
    restart: always
    networks:
      - channelsdb-net
    logging:
      driver: journald
      options:
        tag: channelsdb-api

  web:
    container_name: web
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.production.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/channelsdb2.biodata.ceitec.cz/fullchain.pem:/etc/fullchain.pem:ro
      - /etc/letsencrypt/live/channelsdb2.biodata.ceitec.cz/privkey.pem:/etc/privkey.pem:ro
    restart: always
    networks:
      - channelsdb-net
    logging:
      driver: journald
      options:
        tag: channelsdb-web

# Workaround for OpenStack networking
# See: https://docs.e-infra.cz/compute/openstack/technical-reference/brno-site/faq/
networks:
  channelsdb-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1442